UsitColours/Controllers/FlightController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UsitColours.Areas.Admin.Models;
using UsitColours.AutoMapper;
using UsitColours.Models;
using UsitColours.Services.Contracts;

namespace UsitColours.Controllers
{
    public class FlightController : CommonController
    {
        private readonly IFlightService flightService;
        private readonly ICountryService countryService;

        public FlightController(IFlightService flightService, IMappingService mappingService, ICountryService countryService, IAirportService airportService, ICityService cityService)
            : base(mappingService, cityService, airportService )
        {
            if(flightService == null)
            {
                throw new NullReferenceException("FlightService");
            }

            if (countryService == null)
            {
                throw new NullReferenceException("CountryService");
            }

            this.countryService = countryService;
            this.flightService = flightService;
        }

        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return View("Home");
            }

            int flightId = (int)id;
            var flight = this.flightService.GetDetailedFlight(flightId);

            var mappedFlight = base.MappingService.Map<DetailsFlightViewModel>(flight);

            return PartialView("_DetailFlight", mappedFlight);
        }


        public ActionResult Search()
        {
            var countries = this.countryService.GetAllCountries()
             .Select(x => MappingService.Map<CountryViewModel>(x))
             .Select(c => new SelectListItem() { Text = c.Name, Value = c.Id.ToString() })
             .ToList();

            var viewModel = new SearchViewModel()
            {
                Countries = countries
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Search(int AirportDepartureId, int AirportArrivalId, DateTime DateOfDeparture, int AvailableSeats)
            {
            var flights = this.flightService.GetFlights(AirportDepartureId, AirportArrivalId, DateOfDeparture, AvailableSeats);

            var flightsViewModel = flights
                .Select(f => MappingService.Map<DetailsFlightViewModel>(f))
                .ToList();

            if(flightsViewModel.Count == 0)
            {
                this.TempData["Ticket"] = null;
            }
            else
            {
                this.TempData["Ticket"] = flightsViewModel;

            }

            return PartialView("_FlightSearchResult", flightsViewModel);
        }
    }
}

UsitColours/Controllers/JobController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UsitColours.AutoMapper;
using UsitColours.Models;
using UsitColours.Services.Contracts;

namespace UsitColours.Controllers
{
    public class JobController : BaseController
    {
        private readonly IMappingService mappingService;
        private readonly IJobService jobService;
        private readonly IUserService userService;

        public JobController(IMappingService mappingService, IJobService jobService, IUserService userService)
        {
            if (mappingService == null)
            {
                throw new NullReferenceException("MappingService");
            }

            if (jobService == null)
            {
                throw new NullReferenceException("JobService");
            }

            if (userService == null)
            {
                throw new NullReferenceException("UserService");
            }

            this.mappingService = mappingService;
            this.jobService = jobService;
            this.userService = userService;
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("Home");
            }

            int jobId = (int)id;
            var job = this.jobService.GetJobById(jobId);

            var mappedJob = this.mappingService.Map<JobViewModel>(job);

            return View(mappedJob);
        }

        [Authorize]
        public ActionResult Buy(int jobId)
        {
            string userId = this.GetLoggedUserId();

            bool hasEnoughMoney = this.userService.AttachJobToUser(userId, jobId);

            if (hasEnoughMoney)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // TODO- Message for fail transaction
                return View("Index");
            }
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchResult(string searchTerm, int page = 0)
        {

            var jobsSearchResult = this.jobService.GetAllJobsFromByTerm(searchTerm, page);

            var jobs = jobsSearchResult.Jobs;
            var count = jobsSearchResult.Count;

            var mappedJobs = jobs.Select(j => this.mappingService.Map<JobBaseViewModel>(j))
                .ToList();

            var searchViewModel = new SearchJobViewModel()
            {
                Jobs = mappedJobs,
                Count = count,
                SearchTerm = searchTerm
            };

            return PartialView("_SearchJobResult", searchViewModel);
        }
    }
}

UsitColours/Views/Shared/_DetailFlight.cshtml
@model UsitColours.Models.DetailsFlightViewModel

<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="well">
            <div class="row">
                <div class="col-md-5">
                    <h2>@Model.AirportDepartureName</h2>
                </div>
                <div class="col-md-2">
                    <img src="/Images/flytime.png" alt="Fly time" />
                </div>
                <div class="col-md-5">
                    <h2>@Model.AirportArrivalName</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-md-5" style="color: red; font-size: 45px;">
                    @Model.DateOfDeparture.ToString("hh:mm")
                </div>
                <div class="col-md-2" style="color: #7BB618; font-size:30px">
                    @(Model.DateOfArrival - Model.DateOfDeparture)
                </div>
                <div class="col-md-5" style="color: red; font-size: 45px;">
                    @Model.DateOfArrival.ToString("hh:mm")
                </div>
            </div>
            <p>
                On: @Model.DateOfDeparture.ToString("dd/MM/yyyy")
            </p>
            <p>
                By: @Model.AirlineName
            </p>
            <p>
                Available seats: @Model.AvailableSeats
            </p>
            <p>
                Price: @Model.Price
            </p>
        </div>
    </div>
</div>

UsitColours/Views/Shared/_FlightSearchResult.cshtml
@model IEnumerable<UsitColours.Models.DetailsFlightViewModel>

<h2>FlightSearchResult</h2>
@{
    if (Model.Count() > 0)
    {
        <div class="table-responsive table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <td>Departure airport</td>
                        <td>Arival airport</td>
                    </tr>
                </thead>
                <tbody></tbody>
                @foreach (var flight in Model)
                {
                    <tr>
                        <td>@flight.AirportArrivalName</td>
                        <td>@flight.AirportDepartureName</td>
                    </tr>
                }
                <tr>
                    <td>Total price</td>
                    <td>@Model.Sum(f => f.Price)$</td>
                </tr>
                <tr>
                    <td colspan="2">
                        @Html.ActionLink(
                           "More info", "Index", new { controller = "Ticket" }, new { @class = "btn btn-success" })
                    </td>

                    </tr>
            </table>
            </div>
            } else
            {
            <h1>Cant find available flights</h1>
            }
            }

UsitColours/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("Search Flight", "Search", "Flight", new { area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("Search Job", "Search", "Job", new { area = string.Empty }, null)</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/unobtrusive")


    @section Scripts
{
        <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    }

    @RenderSection("scripts", required: false)
</body>
</html>

UsitColours/Views/Shared/_SearchJobResult.cshtml
@model UsitColours.Models.SearchJobViewModel

<h1>asddaads</h1>
<div class="row">
    @if (Model.Jobs.Count() > 0)
    {
        foreach (var job in Model.Jobs)
        {
            @Html.Partial("_JobBase", job)
        }

        <div class="row">
            <div class="col-md-12 col-md-offset-4">
                <ul class="pagination">
                    @for (int i = 0; i < Model.Count; i++)
                    {

                        <li class="active">
                            @Ajax.ActionLink(i.ToString(),
                                   "SearchResult",
                                   "Job",
                   new { page = i, searchTerm = Model.SearchTerm },
                   new AjaxOptions
                   {
                       UpdateTargetId = "JobResult",
                       InsertionMode = InsertionMode.Replace
                   })
                        </li>
                    }
                    }
                    <li class="waves-effect"><a href="#!"><i class="material-icons"></i></a></li>
                </ul>
            </div>
        </div>
    }
    else
    {   
        <h2 class="center-align">No result found</h2>
    }

</div>